---
- hosts: all
  become: true

  tasks:
  
  - name: stop current running container
    command: docker stop sample-devops-container
    ignore_errors: yes

  - name: remove stopped container
    command: docker rm sample-devops-container
    ignore_errors: yes

  - name: remove docker images
    command: docker rmi bpbhargav28/sample-devops-image:latest
    ignore_errors: yes

  - name: pull docker image from dockerhub
    command: docker pull bpbhargav28/sample-devops-image:latest  

  - name: create container using sample-devops-image
    command: docker run -d --name sample-devops-container -p 8080:8080 bpbhargav28/sample-devops-image:latest
