---
- name: Create pods using deployment 
  hosts: k8s-MGMT-server 
  become: true
  user: root
 
  tasks: 
  - name: create a deployment
    command: kubectl apply -f k8s-deployment.yml

  - name: Update deployment with new pods if image updated in docker hub
    command: kubectl rollout restart deployment.v1.apps/k8s-deployment   

