- hosts: all
# become: true

  tasks:

  - name: build docker image using war file
    command: docker build -t sample-devops-image:latest .
    args:
      chdir: /opt/docker
  
  - name: create create tag to image
    command: docker tag sample-devops-image bpbhargav28/sample-devops-image

  - name: Push image on to docker hub
    command: docker push bpbhargav28/sample-devops-image

  - name: Remove docker images from Ansible server
    command: docker rmi sample-devops-image:latest bpbhargav28/sample-devops-image
    ignore_errors: yes

